vmactions/FreeBSD attempt

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,11 +33,12 @@ jobs:
     - name: Verify Homebrew installation
       run: |
         # brew install gcc
-        find / -name brew
-        if ! command -v brew &> /dev/null; then
-          echo "Homebrew could not be found"
-          exit 1
-        fi
+        brew --help
+        which brew
+#        if ! command -v brew &> /dev/null; then
+#          echo "Homebrew could not be found"
+#          exit 1
+#        fi
 
 
     - name: Set up FreeBSD environment
